# Generated by Django 3.2.5 on 2021-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20210730_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetups',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participants'),
        ),
    ]
