# Generated by Django 3.2.5 on 2021-07-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20210731_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetups',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
